# ----------------------------
# Makefile Options
# ----------------------------

NAME = WNACALC
ICON = icon.png
DESCRIPTION = "GET HACKED"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)